import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "/shared/globals.css"
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} main-page-gradient flex flex-col p-4 lg:p-0`}>
				<Header />
				<main className="mt-10 max-w-screen-xl w-[100%] m-auto flex-1">
					{children}
				</main>
			</body>
		</html>
	);
}
