import type { Metadata } from "next";
import { Rubik_Bubbles } from "next/font/google";
import '../shared/globals.css'
import dynamic from "next/dynamic";
import useTranslation from "next-translate/useTranslation";


const bubbles = Rubik_Bubbles({ weight: '400', subsets: ['latin', 'cyrillic'], })

//TODO: SEO OPTIMIZATION
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
	const { t, lang } = useTranslation()

	return (
		<html lang={lang} >
			<body className={`${bubbles.className} main-page-gradient flex flex-col p-4 lg:p-0`}>
				<main className="mt-10 max-w-screen-xl w-[100%] m-auto flex-1">
					{children}
				</main>
			</body>
		</html>
	);
}
