import type { Metadata } from "next";
import { Rubik_Bubbles } from "next/font/google";
import '../shared/globals.css'

const bubbles = Rubik_Bubbles({ weight: '400', subsets: ['latin', 'cyrillic'], })

//TODO: SEO OPTIMIZATION
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};



export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
	return (
		<html lang={'en'} >
			<body className={`${bubbles.className} main-page-gradient flex flex-col p-4 lg:p-0`}>
				{/* HERE SHOULD BE HEADER BUT IT IS  CLIENT COMPONENT */}
				<main className="mt-10 max-w-screen-xl w-[100%] m-auto flex-1">
					{children}
				</main>
			</body>
		</html>
	);
}
