import type { Metadata } from "next";
import { Rubik_Bubbles } from "next/font/google";
import '../../shared/globals.css'
import { ReactNode } from "react";
import { FormWidget, Header } from "@/components";
import { I18nProviderClient } from "../../../locales/client";

const bubbles = Rubik_Bubbles({ weight: '400', subsets: ['latin', 'cyrillic'], })

//TODO: SEO OPTIMIZATION
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface RootLayoutProps {
    children: ReactNode
    params: {
        locale: string
    }
}

export default function RootLayout({ children, params }: Readonly<RootLayoutProps>) {
    const { locale } = params

    return (
        <html lang={locale} >
            <body className={`${bubbles.className} main-page-gradient flex flex-col p-4 lg:p-0`}>
                <I18nProviderClient locale={locale}>
                    <Header />
                </I18nProviderClient>
                <main className="mt-10 max-w-screen-xl w-[100%] m-auto flex-1">
                    {children}
                </main>
                <FormWidget />
            </body>
        </html>
    );
}